on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Run eslint
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: yarn
      - run: yarn lint
      - run: yarn format --check
  tsc:
    runs-on: ubuntu-latest
    name: Check typescript
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: yarn
      - run: yarn tsc
  test:
    runs-on: ubuntu-latest
    name: Run tests
    needs: [lint, tsc]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: yarn
      - run: yarn test
  e2e:
    runs-on: ubuntu-latest
    name: Run end-to-end tests in docker-compose
    needs: [test]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: yarn
      - run: docker compose -f e2e/docker-compose.yml up -d
      - run: docker compose -f e2e/docker-compose.yml exec playwright yarn e2e
