on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Run eslint
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: yarn
      - run: yarn lint
      - run: yarn format --check
  tsc:
    runs-on: ubuntu-latest
    name: Check typescript
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: yarn
      - run: yarn tsc
  test:
    runs-on: ubuntu-latest
    name: Run tests
    needs: [lint, tsc]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: yarn
      - run: yarn test
  e2e:
    runs-on: ubuntu-latest
    name: Run end-to-end tests
    needs: [test]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: yarn      
      - run: yarn playwright install chromium
      - run: yarn playwright install-deps chromium
      - run: yarn mongo
      - run: yarn e2e
  e2e-dc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Tests
        uses: cloudposse/github-action-docker-compose-test-run@main
        with:
          file: e2e/docker-compose.yml
          service: playwright
          command: yarn && yarn e2e
          registry: registry.hub.docker.com
