on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Run eslint
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '20.x'
      - run: yarn
      - run: yarn lint
      - run: yarn format --check
  tsc:
    runs-on: ubuntu-latest
    name: Check typescript
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '20.x'
      - run: yarn
      - run: yarn tsc
  test:
    runs-on: ubuntu-latest
    name: Run tests
    needs: [lint, tsc]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '20.x'
      - run: yarn
      - run: yarn test
